### ISSUE TITLE
Can´t download the ARM-Compiler 5 from the given link

### ISSUE THREAD

**Issue by Mariam-ui-lab** [sdjkjsdh/AAE3004labsession#10]
https://[download.armfly.com](https://download.armfly.com/armbbs/bbs/96992/ARMCompiler_506_Windows_x86_b960.zip)/armbbs/bbs/96992/ARMCompiler_506_Windows_x86_b960.zip
Is not working.
![Screenshot (24)](https://github.com/sdjkjsdh/AAE3004labsession/assets/133965547/ff102d40-2816-4de4-a658-7584a2f157d0)
![Screenshot (25)](https://github.com/sdjkjsdh/AAE3004labsession/assets/133965547/589c2d4a-a6d8-45ab-abc3-6f8739fdd885)

**Comment by sdjkjsdh** [comment]
Please find the below link to download the .zip file:
https://drive.google.com/file/d/1cYJcB7YIaHvcJ91a6an4mjWajyzoPyxM/view?usp=sharing
