### ISSUE TITLE
Cannot view and access the full screen

### ISSUE THREAD

**Issue by stud-y** [sdjkjsdh/AAE3004labsession#11]
I was following the User Guide and was stuck on Section 2.4. I have tried multiple ways but still cannot get access to the other half.

![image](https://github.com/sdjkjsdh/AAE3004labsession/assets/147638326/7caf1d23-4e64-4f39-b1dc-c6d84b1db417)

**Comment by 222233tommy** [comment]
Hi, please follow the steps at https://www.youtube.com/watch?v=s8lKudS5ntg to install VMware tools. 

When you have install VMWare tools and reboot ubuntu system, follow https://docs.vmware.com/en/VMware-Fusion/13/com.vmware.fusion.using.doc/GUID-9EEA3D9D-7BF8-4599-80A7-ED5D8076E824.html to resize the window.

**Comment by stud-y** [comment]
> Hi, please follow the steps at https://www.youtube.com/watch?v=s8lKudS5ntg to install VMware tools.
> 
> When you have install VMWare tools and reboot ubuntu system, follow https://docs.vmware.com/en/VMware-Fusion/13/com.vmware.fusion.using.doc/GUID-9EEA3D9D-7BF8-4599-80A7-ED5D8076E824.html to resize the window.

Hi, I was unable to install the VMware tools. It keeps telling me there are no such files and I have tried 4 times.

Furthermore, I was unable to set up sources.list, it always states that the command is not found.

**Comment by 222233tommy** [comment]
1. The VMware tools installer is located in the Ubuntu iso file. Maybe this will be helpful: https://www.mmcloud.com/11150.html

**Comment by stud-y** [comment]
> 1. The VMware tools installer is located in the Ubuntu iso file. Maybe this will be helpful: https://www.mmcloud.com/11150.html
> 2. Please try to copy the command directly from "User Guide.pdf" to the Terminal and provide the terminal screenshot to us.

Hi,
For 1. Here is what I received in the terminal: 
![image](https://github.com/sdjkjsdh/AAE3004labsession/assets/147638326/09af8565-5882-4930-94db-71baa2e344d0)

For 2. I got this 
![image](https://github.com/sdjkjsdh/AAE3004labsession/assets/147638326/76a8b4f0-617c-4c5b-9903-0ceb72c88dc1)
Furthermore, I was unable to use the paste function in the virtual machine at all. I have tried the terminal, the browser, and other input sections.

**Comment by sdjkjsdh** [comment]
> > 1. The VMware tools installer is located in the Ubuntu iso file. Maybe this will be helpful: https://www.mmcloud.com/11150.html
> > 2. Please try to copy the command directly from "User Guide.pdf" to the Terminal and provide the terminal screenshot to us.
> 
> Hi, For 1. Here is what I received in the terminal: ![image](https://user-images.githubusercontent.com/147638326/276906850-09af8565-5882-4930-94db-71baa2e344d0.png)
> 
> For 2. I got this ![image](https://user-images.githubusercontent.com/147638326/276909250-76a8b4f0-617c-4c5b-9903-0ceb72c88dc1.png) Furthermore, I was unable to use the paste function in the virtual machine at all. I have tried the terminal, the browser, and other input sections.

I check the content shown in the attached picture, may I confirm that you are trying use the command 'sudo./vmware-install.pl' in a Ubuntu terminal ?
If the problem still not be settled, could you and your group please come to find us for a further discussion? Please send us an email for the face-to-face meeting.

**Comment by stud-y** [comment]
> > > 1. The VMware tools installer is located in the Ubuntu iso file. Maybe this will be helpful: https://www.mmcloud.com/11150.html
> > > 2. Please try to copy the command directly from "User Guide.pdf" to the Terminal and provide the terminal screenshot to us.
> > 
> > 
> > Hi, For 1. Here is what I received in the terminal: ![image](https://user-images.githubusercontent.com/147638326/276906850-09af8565-5882-4930-94db-71baa2e344d0.png)
> > For 2. I got this ![image](https://user-images.githubusercontent.com/147638326/276909250-76a8b4f0-617c-4c5b-9903-0ceb72c88dc1.png) Furthermore, I was unable to use the paste function in the virtual machine at all. I have tried the terminal, the browser, and other input sections.
> 
> I check the content shown in the attached picture, may I confirm that you are trying use the command 'sudo./vmware-install.pl' in a Ubuntu terminal ? If the problem still not be settled, could you and your group please come to find us for a further discussion? Please send us an email for the face-to-face meeting.

Yes, I am trying to use the command 'sudo./vmware-install.pl'. It asked me for a password at first, then it stated that the command was not found. I will send an email for a face-to-face meeting right now.

**Comment by stud-y** [comment]
There is a Full Screen Option, which will enlarge the virtual machine screen as follows.
![20231027182432](https://github.com/sdjkjsdh/AAE3004labsession/assets/147638326/4771b046-a899-4191-b6bc-9113f3108c9f)
![20231027182443](https://github.com/sdjkjsdh/AAE3004labsession/assets/147638326/07446bbe-619b-4b46-b9fa-61b37b4260ee)
Can exit the full screen mode by clicking the icon as shown above.
