### ISSUE TITLE
Unable to open project file WHEELTEC.uvprojx

### ISSUE THREAD

**Issue by stud-y** [sdjkjsdh/AAE3004labsession#19]
muvision IDE shows "Warning #440: Requested device 'STM32F407ZG' is substituted with variant 'STM32F407ZGTx' for target 'FreeRTOS'" when I tried to open WHEELTEC.uvprojx file from source code.

![image](https://github.com/sdjkjsdh/AAE3004labsession/assets/147638326/d8af160c-364f-4df8-b0d1-ef693a28299f)

**Comment by sdjkjsdh** [comment]
please unzip the source file before open it in IDE
