### ISSUE TITLE
Cannot install SSH

### ISSUE THREAD

**Issue by stud-y** [sdjkjsdh/AAE3004labsession#20]
Cannot install SSH using "sudo apt-get install openssh-server". Please see the picture attached.

![image](https://github.com/sdjkjsdh/AAE3004labsession/assets/147638326/06e7e066-4149-4584-b876-966fd81351d4)

**Comment by stud-y** [comment]
Getting the same result when try to install sublime using "sudo apt-get install sublime-text"

![image](https://github.com/sdjkjsdh/AAE3004labsession/assets/147638326/a5394faa-8db4-4207-bee3-16536765d824)

**Comment by sdjkjsdh** [comment]
please fist kill the held process by the following command `$ sudo kill -9 48875`, and reinstall ssh

**Comment by stud-y** [comment]
![684E9FDA0B6FE17DEFC4BD09841D4330](https://github.com/sdjkjsdh/AAE3004labsession/assets/147638326/0b5b30e0-d389-40f5-bd5c-58f0608493b5)
![7041BEC23093781DC6F1743B36CD279A](https://github.com/sdjkjsdh/AAE3004labsession/assets/147638326/65d84522-28ad-4765-9a95-777dfa979b3b)
